services:
  drop_points_crawler:
    build: .
    image: drop-points-crawler
    container_name: mainnet-drop-points-crawler
    volumes:
      - ./config.toml:/usr/src/app/config.toml
      - ./store:/usr/src/app/store
    ports:
      - 3000:3000
    entrypoint: [ "bun", "serve" ]