services:
  drop_points_crawler:
    build: .
    image: drop_points_crawler
    container_name: drop_points_crawler
    volumes:
      - ./config.toml:/usr/src/app/config.toml
      - ./data.db:/usr/src/app/data.db
    ports:
      - 3000:3000
    entrypoint: [ "bun", "serve" ]